# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(730, 430)
        font = QtGui.QFont()
        font.setFamily("Vazir")
        Dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./ui\\data-transformation.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        Dialog.setStyleSheet("background-color: #0F172A;")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 301, 411))
        self.groupBox.setStyleSheet("QGroupBox#groupBox {\n"
"    background-color: #182235;\n"
"    border: 1px solid #2B3957;\n"
"    border-radius: 18px;\n"
"    margin-top: 18px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    padding-top: 20px;\n"
"}\n"
"\n"
"QGroupBox#groupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.catcombo = QtWidgets.QComboBox(self.groupBox)
        self.catcombo.setGeometry(QtCore.QRect(10, 80, 281, 42))
        self.catcombo.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.catcombo.setStyleSheet("QComboBox#catcombo {\n"
"    background-color: #111827;\n"
"    color: white;\n"
"    border: 2px solid #5B5EF5;\n"
"    border-radius: 12px;\n"
"    padding: 8px 12px;\n"
"    font-size: 13px;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"QComboBox#catcombo:hover {\n"
"    border:2px solid #7C83FF;\n"
"}\n"
"\n"
"QComboBox#catcombo:focus {\n"
"    border:2px solid #9D8CFF;\n"
"}\n"
"\n"
"QComboBox#catcombo::drop-down {\n"
"    border:0;\n"
"    width:35px;\n"
"}\n"
"\n"
"QComboBox#catcombo::down-arrow {\n"
"    image:none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background:#1B2437;\n"
"    color:white;\n"
"    border:1px solid #5B5EF5;\n"
"    selection-background-color:#5B5EF5;\n"
"    selection-color:white;\n"
"}")
        self.catcombo.setObjectName("catcombo")
        self.catcombo.addItem("")
        self.updatecat = QtWidgets.QPushButton(self.groupBox)
        self.updatecat.setGeometry(QtCore.QRect(10, 130, 281, 51))
        self.updatecat.setStyleSheet("QPushButton#updatecat{\n"
"\n"
"    background:qlineargradient(\n"
"        x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #5B3DF5,\n"
"        stop:1 #6D6EFF\n"
"    );\n"
"\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:14px;\n"
"\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"\n"
"    padding:12px;\n"
"}\n"
"\n"
"QPushButton#updatecat:hover{\n"
"    background:#6C63FF;\n"
"}\n"
"\n"
"QPushButton#updatecat:pressed{\n"
"    background:#4E3FD5;\n"
"}")
        self.updatecat.setObjectName("updatecat")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(136, 42, 141, 31))
        self.label.setStyleSheet("    background-color: #182235;\n"
"color:white;\n"
"    font-size:14px;\n"
"    font-weight:bold;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 190, 281, 20))
        self.line.setStyleSheet("    background-color: #182235;\n"
"color:white;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 210, 211, 31))
        self.label_2.setStyleSheet("    background-color: #182235;\n"
"color:white;\n"
"    font-size:14px;\n"
"    font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.extractdata = QtWidgets.QPushButton(self.groupBox)
        self.extractdata.setGeometry(QtCore.QRect(10, 270, 281, 51))
        self.extractdata.setStyleSheet("QPushButton#extractdata {\n"
"\n"
"    background: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #0F9D9A,\n"
"        stop:1 #1DB5A8\n"
"    );\n"
"\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 14px;\n"
"\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"\n"
"    padding: 12px;\n"
"}\n"
"\n"
"QPushButton#extractdata:hover {\n"
"\n"
"    background: #22C7B8;\n"
"\n"
"}\n"
"\n"
"QPushButton#extractdata:pressed {\n"
"\n"
"    background: #0D7D77;\n"
"\n"
"}\n"
"\n"
"QPushButton#extractdata:disabled {\n"
"\n"
"    background: #3A4A55;\n"
"    color: #9CA3AF;\n"
"\n"
"}")
        self.extractdata.setObjectName("extractdata")
        self.report = QtWidgets.QPushButton(self.groupBox)
        self.report.setGeometry(QtCore.QRect(10, 330, 281, 51))
        self.report.setStyleSheet("QPushButton#report{\n"
"\n"
"    background:qlineargradient(\n"
"        x1:0,y1:0,x2:1,y2:0,\n"
"        stop:0 #0066FF,\n"
"        stop:1 #3478F6\n"
"    );\n"
"\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius:14px;\n"
"\n"
"    font-size:14px;\n"
"    font-weight:bold;\n"
"\n"
"    padding:12px;\n"
"}\n"
"\n"
"QPushButton#report:hover{\n"
"\n"
"    background:#2A6CFF;\n"
"\n"
"}\n"
"\n"
"QPushButton#report:pressed{\n"
"\n"
"    background:#1557D6;\n"
"\n"
"}")
        self.report.setObjectName("report")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(16, 210, 51, 31))
        self.label_4.setStyleSheet("    background-color: #182235;\n"
"color:white;\n"
"    font-size:14px;\n"
"    font-weight:bold;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(320, 10, 401, 411))
        self.groupBox_2.setStyleSheet("QGroupBox#groupBox_2 {\n"
"    background-color: #182235;\n"
"    border: 1px solid #2B3957;\n"
"    border-radius: 18px;\n"
"    margin-top: 18px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    padding-top: 20px;\n"
"}\n"
"\n"
"QGroupBox#groupBox_2::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(160, 40, 211, 31))
        self.label_3.setStyleSheet("    background-color: #182235;\n"
"color:white;\n"
"    font-size:14px;\n"
"    font-weight:bold;")
        self.label_3.setObjectName("label_3")
        self.deleteselectedcat = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteselectedcat.setGeometry(QtCore.QRect(60, 330, 281, 51))
        self.deleteselectedcat.setStyleSheet("QPushButton#deleteselectedcat{\n"
"\n"
"    background:#E5484D;\n"
"\n"
"    color:white;\n"
"\n"
"    border:none;\n"
"\n"
"    border-radius:14px;\n"
"\n"
"    font-size:14px;\n"
"\n"
"    font-weight:bold;\n"
"\n"
"    padding:12px;\n"
"\n"
"}\n"
"\n"
"QPushButton#deleteselectedcat:hover{\n"
"\n"
"    background:#FF5A60;\n"
"\n"
"}\n"
"\n"
"QPushButton#deleteselectedcat:pressed{\n"
"\n"
"    background:#C63A40;\n"
"\n"
"}")
        self.deleteselectedcat.setObjectName("deleteselectedcat")
        self.listView = QtWidgets.QListWidget(self.groupBox_2)
        self.listView.setGeometry(QtCore.QRect(10, 81, 381, 231))
        self.listView.setStyleSheet("QListWidget#listView{\n"
"\n"
"    background:#111827;\n"
"\n"
"    border:1px solid #2F3C58;\n"
"\n"
"    border-radius:14px;\n"
"\n"
"    color:white;\n"
"\n"
"    outline:none;\n"
"\n"
"    padding:10px;\n"
"\n"
"    font-size:13px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListWidget#listView::item{\n"
"\n"
"    background:#1F2937;\n"
"\n"
"    border:1px solid #334155;\n"
"\n"
"    border-radius:12px;\n"
"\n"
"    padding:12px;\n"
"\n"
"    margin:5px 2px;\n"
"\n"
"    color:#E5E7EB;\n"
"\n"
"}\n"
"\n"
"\n"
"QListWidget#listView::item:hover{\n"
"\n"
"    background:#28344F;\n"
"\n"
"    border:1px solid #5B5EF5;\n"
"\n"
"}\n"
"\n"
"\n"
"QListWidget#listView::item:selected{\n"
"\n"
"    background:#5B5EF5;\n"
"\n"
"    border:1px solid #818CF8;\n"
"\n"
"    color:white;\n"
"\n"
"}\n"
"\n"
"\n"
"/* Scroll Bar */\n"
"\n"
"QScrollBar:vertical{\n"
"\n"
"    background:#111827;\n"
"\n"
"    width:12px;\n"
"\n"
"    margin:8px 4px 8px 0;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical{\n"
"\n"
"    background:#5B5EF5;\n"
"\n"
"    min-height:40px;\n"
"\n"
"    border-radius:6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical:hover{\n"
"\n"
"    background:#818CF8;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical{\n"
"\n"
"    height:0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical{\n"
"\n"
"    background:none;\n"
"\n"
"}\n"
"\n"
"\n"
"/* حذف گوشه اضافی اسکرول */\n"
"\n"
"QScrollBar::corner{\n"
"\n"
"    background:transparent;\n"
"\n"
"}")
        self.listView.setObjectName("listView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "شغل چی"))
        self.catcombo.setItemText(0, _translate("Dialog", "یک دسته بندی انتخاب کنید..."))
        self.updatecat.setText(_translate("Dialog", "آپدیت دسته بندی ها"))
        self.label.setText(_translate("Dialog", " انتخاب دسته بندی :"))
        self.label_2.setText(_translate("Dialog", " عملیات بر اساس دسته بندی :"))
        self.extractdata.setText(_translate("Dialog", "استخراج اطلاعات جدید"))
        self.report.setText(_translate("Dialog", "گزارش گیری"))
        self.label_3.setText(_translate("Dialog", " دسته بندی های انتخاب شده : "))
        self.deleteselectedcat.setText(_translate("Dialog", "حذف دسته بندی انتخاب شده"))
